/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELBOULDER_H__
# define __3D_MODELBOULDER_H__

static POINT    Pointboulder[] =
{
	{3383367, -6801437, 3241555},
	{3383367, -6659641, -3523692},
	{-3383367, -6801437, 3241555},
	{-3383367, -6659641, -3523692},
	{-5659985, -36189, 3383351},
	{-5659985, 105606, -3381896},
	{-5659985, -3280125, -3452859},
	{-5659985, -4339821, 3293149},
	{3383367, -96727, 6271646},
	{-3383367, -96727, 6271646},
	{3383367, -5708567, 6154025},
	{-3383367, -4590913, 6177450},
	{-5303529, -1730580, 5846884},
	{-5199725, -200180, 5822142},
	{6453647, -5117300, 3276853},
	{5848568, -36189, 3383351},
	{6453647, -4513015, -3478700},
	{5588390, 134865, -2996000},
	{5920724, -2514455, 5855193},
	{5397410, -14322, 5582095},
	{-3383367, 180237, -6942619},
	{-3383367, -3923116, -7028624},
	{2849344, -3589801, -6503543},
	{2044900, 166338, -6496314},
	{-4990695, 144284, -6089671},
	{-5286106, -1949837, -6503163},
	{5230938, -2395862, -6132907},
	{5126784, 251319, -5472779},
};

static POLYGON    Polygonboulder[] =
{
	{{0, -65522, -1376}, {0, 2, 3, 1}},
	{{38318, -42310, 32197}, {10, 0, 14, 18}},
	{{-4646, -56918, 32151}, {2, 0, 10, 11}},
	{{-65536, 0, 0}, {5, 6, 7, 4}},
	{{-51648, -40186, -3571}, {3, 2, 7, 6}},
	{{-49106, -35572, -24870}, {3, 6, 25, 21}},
	{{0, -1376, 65522}, {9, 11, 10, 8}},
	{{-13749, -504, 64074}, {11, 9, 13, 12}},
	{{12497, 2038, 64303}, {8, 10, 18, 19}},
	{{-45357, -34045, 32840}, {7, 2, 11, 12}},
	{{-64749, 1042, 10085}, {4, 7, 12, 13}},
	{{64788, 9836, -701}, {15, 14, 16, 17}},
	{{64323, 9745, 7897}, {14, 15, 19, 18}},
	{{34681, -55522, -3067}, {0, 1, 16, 14}},
	{{5400, 1330, -65300}, {23, 22, 21, 20}},
	{{-20971, 5983, -61800}, {20, 21, 25, 24}},
	{{14162, 8617, -63406}, {22, 23, 27, 26}},
	{{3014, -48647, -43810}, {1, 3, 21, 22}},
	{{-64513, 4417, -10636}, {6, 5, 24, 25}},
	{{62658, 10813, -15859}, {17, 16, 26, 27}},
	{{27466, -39262, -44708}, {16, 1, 22, 26}},
};

static ATTR    Attributeboulder[] =
{
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, MOUNTAIN, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
	ATTRIBUTE(Single_Plane, SORT_CEN, GRASS2, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, No_Option),
};

jo_3d_mesh    boulder =
{
	.data =
	{
		Pointboulder,
		28,
		Polygonboulder,
		21,
		Attributeboulder
	}
};



#endif /* !__3D_MODELBOULDER_H__ */
